[programs.devnet]
myepicproject = "FncsSwfyvedwjezBW2Ss4ryCrNPFif71p5DJRo2LXZg6"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/Users/branaust/.config/solana/id.json"

[scripts]
test = "node tests/myepicproject.js"
